CREATE TABLE TEST (
   ID INTEGER,
   PRIMARY KEY (ID)
);

LOAD CLASSES tests.jar;

CREATE PROCEDURE Insert
    AS INSERT INTO TEST (ID) VALUES (?);

CREATE PROCEDURE Print
    AS SELECT * FROM TEST

CREATE PROCEDURE Purge
    AS TRUNCATE TABLE TEST
