/* TODO: File Header */

#ifndef SQL_OMDB_PARSER_H
#define SQL_OMDB_PARSER_H

// C standard library includes
#include <cstdio>
#include <cstdint>
#include <cassert>

// C++ standard library includes
#include <string>

// Project includes
#include "parser/parse.h"
#include "statements/builder.h"
#include "statements/data_definition.h"
#include "statements/data_manipulation.h"

// Needed for the parser generated by Lemon
typedef uint64_t u64;

/**
 *  \brief The datatype passed into the parser from the tokenizer
 */
typedef std::string* Token;

void token_print(Token token);

struct Parse;

void parse();

#define NEVER(X) 0

#endif
