#define TK_SEMICOLON                        1
#define TK_CREATE                           2
#define TK_TABLE                            3
#define TK_LPAREN                           4
#define TK_RPAREN                           5
#define TK_COMMA                            6
#define TK_ID                               7
#define TK_STRING                           8
#define TK_DEFAULT                          9
#define TK_NOT                             10
#define TK_NULL                            11
#define TK_UNIQUE                          12
#define TK_AUTO_INCREMENT                  13
#define TK_OR                              14
#define TK_AND                             15
#define TK_BETWEEN                         16
#define TK_IN                              17
#define TK_ISNULL                          18
#define TK_NOTNULL                         19
#define TK_NE                              20
#define TK_EQ                              21
#define TK_GT                              22
#define TK_LE                              23
#define TK_LT                              24
#define TK_GE                              25
#define TK_DOT                             26
#define TK_INTEGER                         27
#define TK_FLOAT                           28
#define TK_DROP                            29
#define TK_SELECT                          30
#define TK_DISTINCT                        31
#define TK_ALL                             32
#define TK_ASTERISK                        33
#define TK_AS                              34
#define TK_FROM                            35
#define TK_WHERE                           36
#define TK_INSERT                          37
#define TK_INTO                            38
#define TK_VALUES                          39
#define TK_TO_TEXT                         40
#define TK_TO_BLOB                         41
#define TK_TO_NUMERIC                      42
#define TK_TO_INT                          43
#define TK_TO_REAL                         44
#define TK_ISNOT                           45
#define TK_END_OF_FILE                     46
#define TK_ILLEGAL                         47
#define TK_SPACE                           48
#define TK_UNCLOSED_STRING                 49
#define TK_FUNCTION                        50
#define TK_COLUMN                          51
#define TK_AGG_FUNCTION                    52
#define TK_AGG_COLUMN                      53
#define TK_UMINUS                          54
#define TK_UPLUS                           55
#define TK_REGISTER                        56
