#define TK_SEMICOLON                        1
#define TK_CREATE                           2
#define TK_TABLE                            3
#define TK_LPAREN                           4
#define TK_RPAREN                           5
#define TK_COMMA                            6
#define TK_ID                               7
#define TK_STRING                           8
#define TK_DEFAULT                          9
#define TK_NOT                             10
#define TK_NULL                            11
#define TK_AUTO_INCREMENT                  12
#define TK_OR                              13
#define TK_AND                             14
#define TK_BETWEEN                         15
#define TK_IN                              16
#define TK_ISNULL                          17
#define TK_NOTNULL                         18
#define TK_NE                              19
#define TK_EQ                              20
#define TK_GT                              21
#define TK_LE                              22
#define TK_LT                              23
#define TK_GE                              24
#define TK_DOT                             25
#define TK_INTEGER                         26
#define TK_FLOAT                           27
#define TK_DATE                            28
#define TK_TIME                            29
#define TK_DROP                            30
#define TK_SELECT                          31
#define TK_DISTINCT                        32
#define TK_ALL                             33
#define TK_ASTERISK                        34
#define TK_AS                              35
#define TK_FROM                            36
#define TK_WHERE                           37
#define TK_UPDATE                          38
#define TK_SET                             39
#define TK_INSERT                          40
#define TK_INTO                            41
#define TK_VALUES                          42
#define TK_DELETE                          43
#define TK_TO_TEXT                         44
#define TK_TO_BLOB                         45
#define TK_TO_NUMERIC                      46
#define TK_TO_INT                          47
#define TK_TO_REAL                         48
#define TK_ISNOT                           49
#define TK_END_OF_FILE                     50
#define TK_ILLEGAL                         51
#define TK_SPACE                           52
#define TK_UNCLOSED_STRING                 53
#define TK_FUNCTION                        54
#define TK_COLUMN                          55
#define TK_AGG_FUNCTION                    56
#define TK_AGG_COLUMN                      57
#define TK_UMINUS                          58
#define TK_UPLUS                           59
#define TK_REGISTER                        60
