#define TK_SEMICOLON                        1
#define TK_CREATE                           2
#define TK_TABLE                            3
#define TK_LPAREN                           4
#define TK_RPAREN                           5
#define TK_COMMA                            6
#define TK_ID                               7
#define TK_STRING                           8
#define TK_DEFAULT                          9
#define TK_NOT                             10
#define TK_NULL                            11
#define TK_UNIQUE                          12
#define TK_AUTO_INCREMENT                  13
#define TK_TO_TEXT                         14
#define TK_TO_BLOB                         15
#define TK_TO_NUMERIC                      16
#define TK_TO_INT                          17
#define TK_TO_REAL                         18
#define TK_ISNOT                           19
#define TK_END_OF_FILE                     20
#define TK_ILLEGAL                         21
#define TK_SPACE                           22
#define TK_UNCLOSED_STRING                 23
#define TK_FUNCTION                        24
#define TK_COLUMN                          25
#define TK_AGG_FUNCTION                    26
#define TK_AGG_COLUMN                      27
#define TK_UMINUS                          28
#define TK_UPLUS                           29
#define TK_REGISTER                        30
